/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sportsdb;

import java.sql.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FacilitiesPanel extends javax.swing.JPanel {

    private Connection cn;
    public FacilitiesPanel(Connection conn) {
        initComponents();
        cn=conn;
        insertSize.setModel(new SpinnerNumberModel(1,1,99999,1));
        editSize.setModel(new SpinnerNumberModel(1,1,99999,1));
        idRadioButton.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) facilitiesTable.getModel();  
        refreshFacilities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortButtonGroup = new javax.swing.ButtonGroup();
        editFrame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        editLocation = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editSize = new javax.swing.JSpinner();
        submitEdit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        activateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        activeLabel = new javax.swing.JLabel();
        insertFrame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        insertName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        insertLocation = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        insertSize = new javax.swing.JSpinner();
        submitInsert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        locationCombobox = new javax.swing.JComboBox<>();
        newFacilityButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        facilitiesTable = new javax.swing.JTable();
        editFacilityButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        activeCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        idRadioButton = new javax.swing.JRadioButton();
        sizeRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        editFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editFrame.setAlwaysOnTop(true);
        editFrame.setBounds(new java.awt.Rectangle(0, 0, 300, 200));
        editFrame.setMaximumSize(new java.awt.Dimension(300, 200));
        editFrame.setPreferredSize(new java.awt.Dimension(300, 200));
        editFrame.setSize(new java.awt.Dimension(300, 200));
        editFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                editFrameWindowClosing(evt);
            }
        });

        jLabel11.setText("Description");

        editLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoors", "Outdoors" }));

        jLabel12.setText("Location");

        jLabel13.setText("Size");

        editSize.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editSizeInputMethodTextChanged(evt);
            }
        });

        submitEdit.setText("Submit");
        submitEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("m²");

        activateButton.setText("-");
        activateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Active:");

        activeLabel.setForeground(new java.awt.Color(102, 102, 102));
        activeLabel.setText("N/A");

        javax.swing.GroupLayout editFrameLayout = new javax.swing.GroupLayout(editFrame.getContentPane());
        editFrame.getContentPane().setLayout(editFrameLayout);
        editFrameLayout.setHorizontalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(editFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editFrameLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activeLabel))
                    .addGroup(editFrameLayout.createSequentialGroup()
                        .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(24, 24, 24)
                        .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editFrameLayout.createSequentialGroup()
                                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(editSize)
                                    .addComponent(editLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitEdit)
                .addGap(26, 26, 26)
                .addComponent(activateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        editFrameLayout.setVerticalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(editName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(activeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activateButton)
                    .addComponent(submitEdit))
                .addContainerGap())
        );

        editFrame.getAccessibleContext().setAccessibleParent(this);

        insertFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        insertFrame.setTitle("Insert new facility");
        insertFrame.setAlwaysOnTop(true);
        insertFrame.setName("Insert new sport"); // NOI18N
        insertFrame.setSize(new java.awt.Dimension(300, 200));
        insertFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                insertFrameWindowClosing(evt);
            }
        });

        jLabel7.setText("Description");

        jLabel8.setText("Location");

        insertLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoors", "Outdoors" }));
        insertLocation.setSelectedIndex(1);

        jLabel9.setText("Facility Size");

        insertSize.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                insertSizeInputMethodTextChanged(evt);
            }
        });

        submitInsert.setText("Submit");
        submitInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInsertActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("m²");

        javax.swing.GroupLayout insertFrameLayout = new javax.swing.GroupLayout(insertFrame.getContentPane());
        insertFrame.getContentPane().setLayout(insertFrameLayout);
        insertFrameLayout.setHorizontalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertFrameLayout.createSequentialGroup()
                        .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(insertFrameLayout.createSequentialGroup()
                                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(insertSize)
                                    .addComponent(insertLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))))
                    .addComponent(submitInsert))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        insertFrameLayout.setVerticalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(insertLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insertSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(submitInsert)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("Search by Field");

        jLabel3.setText("Name");

        jLabel1.setText("Location");

        locationCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoors", "Outdoors", "Any" }));

        newFacilityButton.setText("New Facility");
        newFacilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFacilityButtonActionPerformed(evt);
            }
        });

        facilitiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Size", "Description", "Location", "Active?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facilitiesTable.setGridColor(new java.awt.Color(243, 243, 243));
        facilitiesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        facilitiesTable.setShowVerticalLines(true);
        facilitiesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(facilitiesTable);
        if (facilitiesTable.getColumnModel().getColumnCount() > 0) {
            facilitiesTable.getColumnModel().getColumn(0).setResizable(false);
            facilitiesTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            facilitiesTable.getColumnModel().getColumn(1).setResizable(false);
            facilitiesTable.getColumnModel().getColumn(1).setPreferredWidth(90);
            facilitiesTable.getColumnModel().getColumn(2).setResizable(false);
            facilitiesTable.getColumnModel().getColumn(2).setPreferredWidth(300);
            facilitiesTable.getColumnModel().getColumn(3).setResizable(false);
            facilitiesTable.getColumnModel().getColumn(3).setPreferredWidth(110);
            facilitiesTable.getColumnModel().getColumn(4).setResizable(false);
        }

        editFacilityButton.setText("Edit Selected");
        editFacilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFacilityButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Apply Filters");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Filters");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        activeCheckBox.setText("Display inactive facilities?");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sortButtonGroup.add(idRadioButton);
        idRadioButton.setText("ID");

        sortButtonGroup.add(sizeRadioButton);
        sizeRadioButton.setText("Size");

        sortButtonGroup.add(nameRadioButton);
        nameRadioButton.setText("Name");

        jLabel6.setText("Sort by");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameRadioButton))
                    .addComponent(sizeRadioButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idRadioButton)
                    .addComponent(nameRadioButton)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editFacilityButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newFacilityButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activeCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)
                            .addComponent(resetButton)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFacilityButton)
                    .addComponent(editFacilityButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editFacilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFacilityButtonActionPerformed
        try{
            editFrame.pack();
            if(facilitiesTable.getRowCount()<=0){
                throw new Exception("No entries to edit!");
            }
            int row = facilitiesTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) facilitiesTable.getModel();
            int selection = (int)model.getValueAt(row, 0);
            editFrame.setVisible(true);
            editFrame.setTitle("Editing facility "+selection);    
            if(((String)model.getValueAt(row, 4)).equals("YES")){
                activateButton.setText("Decomission");
                activeLabel.setText("YES");
            }   
            else{
                activateButton.setText("Restore");
                activeLabel.setText("NO");
            }
            editSize.setValue(Integer.valueOf(((String)(model.getValueAt(row, 1))).split("\\s")[0]));
            editName.setText((String)(model.getValueAt(row, 2)));
            if(((String)(model.getValueAt(row, 3))).equalsIgnoreCase("Outdoors"))
                editLocation.setSelectedIndex(1);
            else
                editLocation.setSelectedIndex(0);

            openPopup();
            editFrame.setVisible(true);
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_editFacilityButtonActionPerformed

    private void newFacilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFacilityButtonActionPerformed
       insertFrame.pack();
       insertFrame.setVisible(true);
       openPopup();
    }//GEN-LAST:event_newFacilityButtonActionPerformed

    private void insertSizeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_insertSizeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_insertSizeInputMethodTextChanged

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{Class.forName(SportsDB.driverClassName);
            
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM select_facilities(?, ?, ?, ?)");
            int sort;            
            String name;
            String location;
            boolean active;
            DefaultTableModel model = (DefaultTableModel) facilitiesTable.getModel();
            if(nameRadioButton.isSelected())
                sort=3;
            else if(sizeRadioButton.isSelected())
                sort=2;
            else 
                sort=1;
            
            if(nameTextfield.getText().equals(""))
                name=null;
            else
                name=nameTextfield.getText();
            
            if(locationCombobox.getSelectedIndex()==2)
                location=null;
            else
                location=(String) locationCombobox.getSelectedItem();
            
            active = !(activeCheckBox.isSelected());
            ps.setObject(1, sort);
            ps.setObject(2, name);
            ps.setObject(3, location);
            ps.setObject(4, active);
            
            ResultSet rs = ps.executeQuery();
            while(model.getRowCount()>0)
                model.removeRow(0);
            while(rs.next()){
                int tempid = rs.getInt("faid");
                String tempsize = rs.getInt("fasize")+" m²";
                String tempname = rs.getString("faname");
                String templocation = rs.getString("falocation");
                String tempactive;
                if(rs.getInt("faactive")==1)
                    tempactive="YES";                    
                else
                    tempactive="NO";
                model.addRow(new Object[]{tempid, tempsize, tempname, templocation, tempactive});
            }
            if(facilitiesTable.getRowCount()>0)
                facilitiesTable.setRowSelectionInterval(0, 0);
        }catch(Exception e){
        showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        refreshFacilities();        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInsertActionPerformed
        
        String fname=insertName.getText();
        String flocation=(String)insertLocation.getSelectedItem();
        Integer fsize = (int)insertSize.getValue();
        
        try{
            if(fname.equals(""))
                throw new Exception("Please enter a description for the facility.");
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM insert_facilities(?, ?, ?)");
            ps.setObject(1, fsize);
            ps.setObject(2, fname);
            ps.setObject(3, flocation);
            ps.executeQuery();

            insertFrame.setVisible(false);
            closePopup();
            refreshFacilities();
            insertFrame.dispose();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_submitInsertActionPerformed

    private void insertFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_insertFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_insertFrameWindowClosing

    private void editFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_editFrameWindowClosing

    private void activateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateButtonActionPerformed
        try{
            int row = facilitiesTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) facilitiesTable.getModel();
            int selection = (int)model.getValueAt(row, 0);
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM active_facilities(?)");
            ps.setObject(1, selection);
            ps.executeQuery();
            closePopup();
            refreshFacilities();
            editFrame.setVisible(false);
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_activateButtonActionPerformed

    private void submitEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditActionPerformed

        String fname=editName.getText();
        String flocation=(String)editLocation.getSelectedItem();
        Integer fsize = (int)editSize.getValue();
        int fid = (int)facilitiesTable.getModel().getValueAt(facilitiesTable.getSelectedRow(), 0);
        try{
            if(fname.equals(""))
            throw new Exception("Please enter a description for the facility.");

            PreparedStatement ps = cn.prepareStatement("SELECT * FROM edit_facilities(?, ?, ?, ?)");
            ps.setObject(1, fid);
            ps.setObject(2, fsize);
            ps.setObject(3, fname);
            ps.setObject(4, flocation);
            ps.executeQuery();

            editFrame.setVisible(false);
            editFrame.dispose();
            closePopup();
            refreshFacilities();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_submitEditActionPerformed

    private void editSizeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editSizeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editSizeInputMethodTextChanged

    private void refreshFacilities(){
        DefaultTableModel model = (DefaultTableModel) facilitiesTable.getModel();
        try{Class.forName(SportsDB.driverClassName);
            while(model.getRowCount()>0)
                model.removeRow(0);
            Statement statement = cn.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM select_facilities(1, NULL, NULL, TRUE)");
            while(rs.next()){
                int id = rs.getInt("faid");
                String size = rs.getInt("fasize")+" m²";
                String name = rs.getString("faname");
                String location = rs.getString("falocation");
                String active;
                if(rs.getInt("faactive")==1)
                    active="YES";                    
                else
                    active="NO";
                model.addRow(new Object[]{id, size, name, location, active});
            }
            if(facilitiesTable.getRowCount()>0)
                facilitiesTable.setRowSelectionInterval(0, 0);
            else
                showMessageDialog(null, "No entries for table, please add some!");
            nameTextfield.setText("");
            locationCombobox.setSelectedIndex(2);
            activeCheckBox.setSelected(false);
            idRadioButton.setSelected(true);
        }catch(Exception e){
         showMessageDialog(null, e.getMessage());
        }
    }

    private void openPopup(){
       newFacilityButton.setEnabled(false);
       editFacilityButton.setEnabled(false);
       facilitiesTable.setEnabled(false);
       searchButton.setEnabled(false);
       resetButton.setEnabled(false);
    }
    
    private void closePopup(){
        newFacilityButton.setEnabled(true);
        editFacilityButton.setEnabled(true);
        facilitiesTable.setEnabled(true);
        searchButton.setEnabled(true);
        resetButton.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateButton;
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JLabel activeLabel;
    private javax.swing.JButton editFacilityButton;
    private javax.swing.JFrame editFrame;
    private javax.swing.JComboBox<String> editLocation;
    private javax.swing.JTextField editName;
    private javax.swing.JSpinner editSize;
    private javax.swing.JTable facilitiesTable;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JFrame insertFrame;
    private javax.swing.JComboBox<String> insertLocation;
    private javax.swing.JTextField insertName;
    private javax.swing.JSpinner insertSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> locationCombobox;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JButton newFacilityButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JRadioButton sizeRadioButton;
    private javax.swing.ButtonGroup sortButtonGroup;
    private javax.swing.JButton submitEdit;
    private javax.swing.JButton submitInsert;
    // End of variables declaration//GEN-END:variables
}
