/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sportsdb;

import java.sql.*;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;

import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;


/**
 *
 * @author User
 */
public class MembersPanel extends javax.swing.JPanel {

    private Connection cn;
    public MembersPanel(Connection conn) {
        initComponents();
        cn=conn;
        idRadioButton.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) membersTable.getModel();  
        refreshMembers();

        
        ageFromSpinner.setModel(new SpinnerNumberModel(0,0,100,1));
        ageToSpinner.setModel(new SpinnerNumberModel(0,0,100,1));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortButtonGroup = new javax.swing.ButtonGroup();
        editFrame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        submitEdit = new javax.swing.JButton();
        activateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        activeLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        editSurname = new javax.swing.JTextField();
        insertFrame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        insertName = new javax.swing.JTextField();
        submitInsert = new javax.swing.JButton();
        insertSurname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        insertBirthYear = new javax.swing.JFormattedTextField();
        insertBirthMonth = new javax.swing.JFormattedTextField();
        insertBirthDay = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        insertSexCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        sexCombobox = new javax.swing.JComboBox<>();
        newMemberButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        membersTable = new javax.swing.JTable();
        editMemberButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        activeCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        idRadioButton = new javax.swing.JRadioButton();
        joinRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        surnameRadioButton = new javax.swing.JRadioButton();
        ageRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        surnameTextfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        idTextField = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        teamTextField = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ageFromSpinner = new javax.swing.JSpinner();
        ageToSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        joinFromYear = new javax.swing.JFormattedTextField();
        joinFromMonth = new javax.swing.JFormattedTextField();
        joinFromDay = new javax.swing.JFormattedTextField();
        joinToYear = new javax.swing.JFormattedTextField();
        joinToMonth = new javax.swing.JFormattedTextField();
        joinToDay = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        editFrame.setAlwaysOnTop(true);
        editFrame.setBounds(new java.awt.Rectangle(0, 0, 300, 200));
        editFrame.setMaximumSize(new java.awt.Dimension(300, 200));
        editFrame.setPreferredSize(new java.awt.Dimension(300, 200));
        editFrame.setSize(new java.awt.Dimension(300, 200));
        editFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                editFrameWindowClosing(evt);
            }
        });

        jLabel11.setText("Name");

        submitEdit.setText("Submit");
        submitEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditActionPerformed(evt);
            }
        });

        activateButton.setText("-");
        activateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Active:");

        activeLabel.setForeground(new java.awt.Color(102, 102, 102));
        activeLabel.setText("N/A");

        jLabel26.setText("Surname");

        javax.swing.GroupLayout editFrameLayout = new javax.swing.GroupLayout(editFrame.getContentPane());
        editFrame.getContentPane().setLayout(editFrameLayout);
        editFrameLayout.setHorizontalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editFrameLayout.createSequentialGroup()
                        .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFrameLayout.createSequentialGroup()
                                .addComponent(submitEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(activateButton))
                            .addGroup(editFrameLayout.createSequentialGroup()
                                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFrameLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        editFrameLayout.setVerticalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(editSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(activeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        editFrame.getAccessibleContext().setAccessibleParent(this);

        insertFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        insertFrame.setTitle("Insert new member");
        insertFrame.setAlwaysOnTop(true);
        insertFrame.setName("Insert new sport"); // NOI18N
        insertFrame.setSize(new java.awt.Dimension(300, 200));
        insertFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                insertFrameWindowClosing(evt);
            }
        });

        jLabel7.setText("Name");

        submitInsert.setText("Submit");
        submitInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInsertActionPerformed(evt);
            }
        });

        jLabel9.setText("Surname");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("(YYYY - MM - DD)");

        jLabel24.setText("Date of Birth");

        jLabel25.setText("Sex");

        insertSexCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout insertFrameLayout = new javax.swing.GroupLayout(insertFrame.getContentPane());
        insertFrame.getContentPane().setLayout(insertFrameLayout);
        insertFrameLayout.setHorizontalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertFrameLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertSexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitInsert))
                    .addGroup(insertFrameLayout.createSequentialGroup()
                        .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(insertSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(insertFrameLayout.createSequentialGroup()
                                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(insertFrameLayout.createSequentialGroup()
                                        .addComponent(insertBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(insertBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(insertBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(insertFrameLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel23)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertFrameLayout.setVerticalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(insertSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(insertSexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Sex");

        sexCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Male", "Female" }));

        newMemberButton.setText("New Member");
        newMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        membersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Date of Birth", "Join Date", "Active?", "Sex", "Teams"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        membersTable.setGridColor(new java.awt.Color(243, 243, 243));
        membersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        membersTable.setShowVerticalLines(true);
        membersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(membersTable);
        if (membersTable.getColumnModel().getColumnCount() > 0) {
            membersTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            membersTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            membersTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            membersTable.getColumnModel().getColumn(3).setPreferredWidth(300);
            membersTable.getColumnModel().getColumn(4).setPreferredWidth(200);
            membersTable.getColumnModel().getColumn(5).setPreferredWidth(80);
            membersTable.getColumnModel().getColumn(6).setPreferredWidth(80);
            membersTable.getColumnModel().getColumn(7).setPreferredWidth(300);
        }

        editMemberButton.setText("Edit Selected");
        editMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMemberButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Apply Filters");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Filters");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        activeCheckBox.setText("Display inactive members?");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sortButtonGroup.add(idRadioButton);
        idRadioButton.setText("ID");

        sortButtonGroup.add(joinRadioButton);
        joinRadioButton.setText("Join Date");

        sortButtonGroup.add(nameRadioButton);
        nameRadioButton.setText("Name");

        jLabel6.setText("Sort by");

        sortButtonGroup.add(surnameRadioButton);
        surnameRadioButton.setText("Surname");

        sortButtonGroup.add(ageRadioButton);
        ageRadioButton.setText("Age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idRadioButton)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageRadioButton)
                            .addComponent(surnameRadioButton)
                            .addComponent(joinRadioButton))
                        .addGap(7, 7, 7))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinRadioButton)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageRadioButton)
                    .addComponent(idRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRadioButton)
                    .addComponent(surnameRadioButton)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Search by Field");

        jLabel3.setText("Name");

        jLabel13.setText("Surname");

        jLabel14.setText("ID");

        jLabel15.setText("Team ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextfield)
                            .addComponent(surnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(surnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(teamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel16.setText("Age");

        jLabel17.setText("From:");

        jLabel18.setText("To:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setText("Join Date");

        jLabel20.setText("From:");

        jLabel21.setText("To:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("(YYYY-MM-DD)");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("(0 for any age)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editMemberButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newMemberButton))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinFromYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinFromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinFromDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(joinToYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinToDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activeCheckBox))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(resetButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel4))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ageFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(ageToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(joinFromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinFromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinFromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(joinToYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinToDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMemberButton)
                    .addComponent(editMemberButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMemberButtonActionPerformed
        try{
            if(membersTable.getRowCount()<=0){
                throw new Exception("No entries to edit!");
            }
            int row = membersTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) membersTable.getModel();
            int selection = (int)model.getValueAt(row, 0);
            editFrame.pack();
            editFrame.setVisible(true);
            editFrame.setTitle("Editing Member "+selection);
            if(((String)model.getValueAt(row, 5)).equals("YES")){
                activateButton.setText("Retire");
                activeLabel.setText("YES");
            }   
            else{
                activateButton.setText("Restore");
                activeLabel.setText("NO");
            }
            editName.setText((String)(model.getValueAt(row, 1)));
            editSurname.setText((String)(model.getValueAt(row, 2)));  

            openPopup();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_editMemberButtonActionPerformed

    private void newMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberButtonActionPerformed
       insertFrame.pack();
       insertFrame.setVisible(true);
       
       openPopup();
    }//GEN-LAST:event_newMemberButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        if(!checkTextBoxes())
            ;
        else{
        int sort=1;
        String fname;
        String lname;
        String sex;
        Integer agef;
        Integer aget;
        Integer meid;
        String datef;
        String datet;
        Integer team;
        boolean active;
        
        if(idRadioButton.isSelected())
            sort=1;
        else if(nameRadioButton.isSelected())
            sort=2;
        else if(surnameRadioButton.isSelected())
            sort=3;
        else if(ageRadioButton.isSelected())
            sort=4;
        else if(joinRadioButton.isSelected())
            sort=5;
        
        if(nameTextfield.getText().equals(""))
            fname=null;
        else
            fname=nameTextfield.getText();
        if(surnameTextfield.getText().equals(""))
            lname=null;
        else
            lname=surnameTextfield.getText();
        
        if(sexCombobox.getSelectedIndex()==0)
            sex=null;
        else
            sex=(String)sexCombobox.getSelectedItem();
        
        if((int)ageFromSpinner.getValue()==0)
            agef=null;
        else
            agef=(int)ageFromSpinner.getValue();
        if((int)ageToSpinner.getValue()==0)
            aget=null;
        else
            aget=(int)ageToSpinner.getValue();
        
        if(idTextField.getText().equals(""))
            meid=null;
        else
            meid=Integer.parseInt(idTextField.getText());
        if(teamTextField.getText().equals(""))
            team=null;
        else
            team=Integer.parseInt(teamTextField.getText());
        

        if(joinFromYear.getText().equals("")||joinFromMonth.getText().equals("")||joinFromDay.getText().equals(""))
            datef=null;
        else{
            datef=joinFromYear.getText()+"-"+joinFromMonth.getText()+"-"+joinFromDay.getText();           
        }
        if(joinToYear.getText().equals("")||joinToMonth.getText().equals("")||joinToDay.getText().equals(""))
            datet=null;
        else{
            datet=joinToYear.getText()+"-"+joinToMonth.getText()+"-"+joinToDay.getText();  
        }
        active=!(activeCheckBox.isSelected());
        searchMembers(sort,fname,lname,sex,agef,aget,meid,datef,datet,team,active);
        }   
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        refreshMembers();        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInsertActionPerformed
        
        String fname=insertName.getText();
        String lname=insertSurname.getText();
        String sex=(String)insertSexCombobox.getSelectedItem();
        String bdate="";
        
        try{
            if(fname.equals(""))
                throw new Exception("Please enter a first name.");
            if(lname.equals(""))
                throw new Exception("Please enter a surname.");
            String text=insertBirthYear.getText();
            if(text.equals("")){
                throw new Exception("Please enter year of birth");
            }
            if(!(text.matches("[0-9]{4}"))){
                insertBirthYear.setText("");
                throw new Exception("Invalid year of birth");
            }
            text=insertBirthMonth.getText();
            if(text.equals("")){
                throw new Exception("Please enter month of birth");
            }
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<13&&Integer.parseInt(text)>0)){
                    insertBirthMonth.setText("");
                    throw new Exception("Invalid month of birth");                    
                }
            text=insertBirthDay.getText();
            if(text.equals("")){
                throw new Exception("Please enter day of birth");
            }
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<31&&Integer.parseInt(text)>0)){
                    insertBirthDay.setText("");
                    throw new Exception("Invalid day of birth");
                }
            bdate=insertBirthYear.getText()+"-"+insertBirthMonth.getText()+"-"+insertBirthDay.getText();
            PreparedStatement ps;
            ps = cn.prepareStatement("SELECT * FROM insert_members(?, ?, ?::date, ?)");
            ps.setObject(1, fname);
            ps.setObject(2, lname);
            ps.setObject(3, bdate);
            ps.setObject(4, sex);
            ps.executeQuery();

            insertFrame.setVisible(false);
            closePopup();
            refreshMembers();
            insertFrame.dispose();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_submitInsertActionPerformed

    private void insertFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_insertFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_insertFrameWindowClosing

    private void editFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_editFrameWindowClosing

    private void activateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateButtonActionPerformed
        try{
            int row = membersTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) membersTable.getModel();
            int selection = (int)model.getValueAt(row, 0);
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM active_members(?)");
            ps.setObject(1, selection);
            ps.executeQuery();
            closePopup();
            refreshMembers();
            editFrame.setVisible(false);
            editFrame.dispose();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_activateButtonActionPerformed

    private void submitEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditActionPerformed

        String fname=editName.getText();
        String lname=editSurname.getText();
        int tid = (int)membersTable.getModel().getValueAt(membersTable.getSelectedRow(), 0);      
        try{
            if(fname.equals(""))
                throw new Exception("Please enter a name for the member.");
            if(lname.equals(""))
                throw new Exception("Please enter a surname for the member.");
            PreparedStatement ps;   
            ps = cn.prepareStatement("SELECT * FROM edit_members(?, ?, ?)");
            ps.setObject(1, tid);
            ps.setObject(2, fname);
            ps.setObject(3, lname);
            ps.executeQuery();

            editFrame.setVisible(false);
            closePopup();
            refreshMembers();
            editFrame.dispose();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_submitEditActionPerformed

    private void refreshMembers(){

        searchMembers(1,null,null,null,null,null,null,null,null,null,true);
        nameTextfield.setText("");
        surnameTextfield.setText("");
        idTextField.setText("");
        teamTextField.setText("");
        ageFromSpinner.setValue(0);
        ageToSpinner.setValue(0);
        sexCombobox.setSelectedIndex(0);
        joinFromYear.setText("");
        joinFromMonth.setText("");
        joinFromDay.setText("");
        joinToYear.setText("");
        joinToMonth.setText("");
        joinToDay.setText("");
        idRadioButton.setSelected(true);
        activeCheckBox.setSelected(false);
        if(membersTable.getRowCount()>0)
            membersTable.setRowSelectionInterval(0, 0);        
        else
            showMessageDialog(null, "No entries for table, please add some!");
    }
    
    private void searchMembers(Integer sort,String fname, String lname, String sex, Integer agef, Integer aget, Integer meid, String datef, String datet, Integer team, boolean active){
        DefaultTableModel model = (DefaultTableModel) membersTable.getModel();
        try{Class.forName(SportsDB.driverClassName);
            while(model.getRowCount()>0)
                model.removeRow(0);
            
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM select_members(?, ?, ?, ?, ?, ?, ?, ?::date, ?::date, ?, ?)");
            ps.setObject(1, sort);
            ps.setObject(2, fname);
            ps.setObject(3, lname);
            ps.setObject(4, sex);
            ps.setObject(5, agef);
            ps.setObject(6, aget);
            ps.setObject(7, meid);
            ps.setObject(8, datef);
            ps.setObject(9, datet);
            ps.setObject(10, team);
            ps.setObject(11, active);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                int tempid = rs.getInt("meid");
                String tempname = rs.getString("mfname");
                String tempsurname = rs.getString("mlname");
                String tempbirth = (rs.getString("mbirth")+"(Aged: "+rs.getInt("mage")+")");
                String tempjoined = rs.getString("mjoined");
                
                String tempactive;
                if(rs.getInt("mactive")==1)
                    tempactive="YES";                    
                else
                    tempactive="NO";
                String tempsex = rs.getString("msex");
                model.addRow(new Object[]{tempid, tempname, tempsurname, tempbirth, tempjoined, tempactive, tempsex});
            }
            for(int i = 0; i<membersTable.getRowCount(); i++){
                String teams = "";
                ps = cn.prepareStatement("SELECT * FROM team_of_member(?)");
                ps.setObject(1, membersTable.getValueAt(i, 0));
                rs = ps.executeQuery();
                while(rs.next())
                    teams=teams+rs.getString("tname")+" | ";
                membersTable.setValueAt(teams, i, 7);
            }
        }catch(Exception e){
         showMessageDialog(null, e.getMessage());
        }
    }

    private void openPopup(){
       newMemberButton.setEnabled(false);
       editMemberButton.setEnabled(false);
       membersTable.setEnabled(false);
       searchButton.setEnabled(false);
       resetButton.setEnabled(false);
    }
    
    private void closePopup(){
        newMemberButton.setEnabled(true);
        editMemberButton.setEnabled(true);
        membersTable.setEnabled(true);
        searchButton.setEnabled(true);
        resetButton.setEnabled(true);
    }
    
    private boolean checkTextBoxes(){
        boolean result=true;
        String text;
        text=idTextField.getText();
        if(!(text.matches("[0-9]{6}")||text.equals(""))){
            showMessageDialog(null, "Invalid member id");
            idTextField.setText("");
            result=false;
        }
        text=teamTextField.getText();
        if(!(text.matches("[0-9]{3}")||text.equals(""))){
            showMessageDialog(null, "Invalid team id");
            teamTextField.setText("");
            result=false;
        }
        text=joinFromYear.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+"))&&text.length()==4){
                showMessageDialog(null, "Invalid year");
                joinFromYear.setText("");
                result=false;
            }
        }
        text=joinToYear.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+"))&&text.length()==4){
                showMessageDialog(null, "Invalid year");
                joinToYear.setText("");
                result=false;
            }
        }
        text=joinFromMonth.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<13&&Integer.parseInt(text)>0))
                {
                    showMessageDialog(null, "Invalid Month");
                    joinFromMonth.setText("");
                    result=false;
                }
        }
        text=joinToMonth.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<13&&Integer.parseInt(text)>0))
                {
                    showMessageDialog(null, "Invalid Month");
                    joinToMonth.setText("");
                    result=false;
                }
        }
        text=joinFromDay.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<31&&Integer.parseInt(text)>0))
                {
                    showMessageDialog(null, "Invalid Day");
                    joinFromDay.setText("");
                    result=false;
                }
        }
        text=joinToDay.getText();
        if(!(text.equals(""))){
            if(!(text.matches("[0-9]+")))
                if(!(Integer.parseInt(text)<31&&Integer.parseInt(text)>0))
                {
                    showMessageDialog(null, "Invalid Day");
                    joinToDay.setText("");
                    result=false;
                }
        }
        return result;
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateButton;
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JLabel activeLabel;
    private javax.swing.JSpinner ageFromSpinner;
    private javax.swing.JRadioButton ageRadioButton;
    private javax.swing.JSpinner ageToSpinner;
    private javax.swing.JFrame editFrame;
    private javax.swing.JButton editMemberButton;
    private javax.swing.JTextField editName;
    private javax.swing.JTextField editSurname;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JFormattedTextField idTextField;
    private javax.swing.JFormattedTextField insertBirthDay;
    private javax.swing.JFormattedTextField insertBirthMonth;
    private javax.swing.JFormattedTextField insertBirthYear;
    private javax.swing.JFrame insertFrame;
    private javax.swing.JTextField insertName;
    private javax.swing.JComboBox<String> insertSexCombobox;
    private javax.swing.JTextField insertSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField joinFromDay;
    private javax.swing.JFormattedTextField joinFromMonth;
    private javax.swing.JFormattedTextField joinFromYear;
    private javax.swing.JRadioButton joinRadioButton;
    private javax.swing.JFormattedTextField joinToDay;
    private javax.swing.JFormattedTextField joinToMonth;
    private javax.swing.JFormattedTextField joinToYear;
    private javax.swing.JTable membersTable;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JButton newMemberButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sexCombobox;
    private javax.swing.ButtonGroup sortButtonGroup;
    private javax.swing.JButton submitEdit;
    private javax.swing.JButton submitInsert;
    private javax.swing.JRadioButton surnameRadioButton;
    private javax.swing.JTextField surnameTextfield;
    private javax.swing.JFormattedTextField teamTextField;
    // End of variables declaration//GEN-END:variables
}
