/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sportsdb;

import java.sql.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SportsPanel extends javax.swing.JPanel {

    private Connection cn;
    public SportsPanel(Connection conn) {
        initComponents();
        cn=conn;
        ageSpinner.setModel(new SpinnerNumberModel(0,0,100,1));
        insertAge.setModel(new SpinnerNumberModel(0,0,100,1));
        editAge.setModel(new SpinnerNumberModel(50,0,100,1));
        idRadioButton.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) sportsTable.getModel();
        refreshSports();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortButtonGroup = new javax.swing.ButtonGroup();
        editFrame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        editSex = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editAge = new javax.swing.JSpinner();
        submitEdit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        insertFrame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        insertName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        insertSex = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        insertAge = new javax.swing.JSpinner();
        submitInsert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sexCombobox = new javax.swing.JComboBox<>();
        ageSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        newSportButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sportsTable = new javax.swing.JTable();
        editSportButton = new javax.swing.JButton();
        nameRadioButton = new javax.swing.JRadioButton();
        idRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        editFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editFrame.setAlwaysOnTop(true);
        editFrame.setSize(new java.awt.Dimension(300, 200));
        editFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                editFrameWindowClosing(evt);
            }
        });

        jLabel11.setText("Sport Name");

        editSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Any" }));
        editSex.setSelectedIndex(2);

        jLabel12.setText("Sport Sex");

        jLabel13.setText("Sport Age");

        editAge.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editAgeInputMethodTextChanged(evt);
            }
        });

        submitEdit.setText("Submit");
        submitEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("(set to 0 for any age)");

        javax.swing.GroupLayout editFrameLayout = new javax.swing.GroupLayout(editFrame.getContentPane());
        editFrame.getContentPane().setLayout(editFrameLayout);
        editFrameLayout.setHorizontalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editFrameLayout.createSequentialGroup()
                        .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editFrameLayout.createSequentialGroup()
                                .addComponent(editAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(editSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitEdit))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editFrameLayout.setVerticalGroup(
            editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitEdit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        editFrame.getAccessibleContext().setAccessibleParent(this);

        insertFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        insertFrame.setTitle("Insert new sport");
        insertFrame.setAlwaysOnTop(true);
        insertFrame.setName("Insert new sport"); // NOI18N
        insertFrame.setSize(new java.awt.Dimension(300, 200));
        insertFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                insertFrameWindowClosing(evt);
            }
        });

        jLabel7.setText("Sport Name");

        jLabel8.setText("Sport Sex");

        insertSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Any" }));
        insertSex.setSelectedIndex(2);

        jLabel9.setText("Sport Age");

        insertAge.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                insertAgeInputMethodTextChanged(evt);
            }
        });

        submitInsert.setText("Submit");
        submitInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInsertActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("(set to 0 for any age)");

        javax.swing.GroupLayout insertFrameLayout = new javax.swing.GroupLayout(insertFrame.getContentPane());
        insertFrame.getContentPane().setLayout(insertFrameLayout);
        insertFrameLayout.setHorizontalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertFrameLayout.createSequentialGroup()
                        .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertFrameLayout.createSequentialGroup()
                                .addComponent(insertAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(insertSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(submitInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertFrameLayout.setVerticalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(insertSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insertAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(submitInsert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Search by Field");

        jLabel3.setText("Name");

        jLabel1.setText("Sex");

        sexCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Any" }));
        sexCombobox.setSelectedIndex(2);

        ageSpinner.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ageSpinnerInputMethodTextChanged(evt);
            }
        });

        jLabel5.setText("Max Age");

        newSportButton.setText("New Sport");
        newSportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSportButtonActionPerformed(evt);
            }
        });

        sportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sex", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sportsTable.setGridColor(new java.awt.Color(243, 243, 243));
        sportsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sportsTable.setShowVerticalLines(true);
        sportsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(sportsTable);
        if (sportsTable.getColumnModel().getColumnCount() > 0) {
            sportsTable.getColumnModel().getColumn(0).setResizable(false);
            sportsTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            sportsTable.getColumnModel().getColumn(1).setResizable(false);
            sportsTable.getColumnModel().getColumn(1).setPreferredWidth(400);
            sportsTable.getColumnModel().getColumn(2).setResizable(false);
            sportsTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            sportsTable.getColumnModel().getColumn(3).setResizable(false);
            sportsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        editSportButton.setText("Edit Selected");
        editSportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSportButtonActionPerformed(evt);
            }
        });

        sortButtonGroup.add(nameRadioButton);
        nameRadioButton.setText("Name");

        sortButtonGroup.add(idRadioButton);
        idRadioButton.setText("ID");

        jLabel6.setText("Sort by");

        searchButton.setText("Apply Filters");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Filters");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(sexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idRadioButton)
                            .addComponent(nameRadioButton))
                        .addGap(9, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editSportButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newSportButton)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(idRadioButton)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRadioButton)
                    .addComponent(resetButton)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSportButton)
                    .addComponent(newSportButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ageSpinnerInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ageSpinnerInputMethodTextChanged

    }//GEN-LAST:event_ageSpinnerInputMethodTextChanged

    private void editSportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSportButtonActionPerformed
        try{
            if(sportsTable.getRowCount()<=0){
                throw new Exception("No entries to edit!");
            }
            int row = sportsTable.getSelectedRow();
            int selection = (int)sportsTable.getModel().getValueAt(row, 0);
            editFrame.pack();
            editFrame.setVisible(true);
            openPopup();
            editFrame.setTitle("Editing sport "+selection);
            
            editName.setText((String)(sportsTable.getModel().getValueAt(row, 1)));
            if (sportsTable.getModel().getValueAt(row, 2)==null)
                editSex.setSelectedIndex(2);
            else if(((String)(sportsTable.getModel().getValueAt(row, 2))).equalsIgnoreCase("Male"))
                editSex.setSelectedIndex(0);
            else if(((String)(sportsTable.getModel().getValueAt(row, 2))).equalsIgnoreCase("Female"))
                editSex.setSelectedIndex(1);
            else
                editSex.setSelectedIndex(2);
            
            if (sportsTable.getModel().getValueAt(row, 3)==null)
                editAge.setValue(0);
            else
                editAge.setValue((int)sportsTable.getModel().getValueAt(row, 3));
            
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_editSportButtonActionPerformed

    private void newSportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSportButtonActionPerformed
       insertFrame.pack();
       insertFrame.setVisible(true);       
       openPopup();
    }//GEN-LAST:event_newSportButtonActionPerformed

    private void insertAgeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_insertAgeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_insertAgeInputMethodTextChanged

    private void editAgeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editAgeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editAgeInputMethodTextChanged

    private void submitEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditActionPerformed
        
        String sname=editName.getText();
        String ssex=(String)editSex.getSelectedItem();
        Integer sage = (int)editAge.getValue();
        int sid = (int)sportsTable.getModel().getValueAt(sportsTable.getSelectedRow(), 0);
        try{
            if(sname.equals(""))
                throw new Exception("Please enter a name.");
            if(ssex.equalsIgnoreCase("Any"))
                ssex = null;
            if((sage==0))
                sage = null;
        PreparedStatement ps = cn.prepareStatement("SELECT * FROM edit_sports(?, ?, ?, ?)");
        ps.setObject(1, sid);
        ps.setObject(2, sname);
        ps.setObject(3, ssex);
        ps.setObject(4, sage);
        ps.executeQuery();
        
        insertFrame.setVisible(false);
        insertFrame.dispose();
        closePopup();
        refreshSports();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_submitEditActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{Class.forName(SportsDB.driverClassName);
            
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM select_sports(?, ?, ?, ?)");
            int sort;            
            String sex;
            Integer age;
            String name;
            DefaultTableModel model = (DefaultTableModel) sportsTable.getModel();
            if(nameRadioButton.isSelected())
                sort=2;
            else
                sort=1;
            
            if(nameTextfield.getText().equals(""))
                name=null;
            else
                name=nameTextfield.getText();
            
            if(sexCombobox.getSelectedIndex()==2)
                sex=null;
            else
                sex=(String) sexCombobox.getSelectedItem();
            
            if((int)ageSpinner.getValue()<=0)
                age= null;
            else
                age=(int)ageSpinner.getValue();
            ps.setObject(1, sort);
            ps.setObject(2, sex);
            ps.setObject(3, age);
            ps.setObject(4, name);
            
            ResultSet rs = ps.executeQuery();
            while(model.getRowCount()>0)
                model.removeRow(0);
            while(rs.next()){
                int tempid = rs.getInt("sportid");
                String tempname = rs.getString("sportname");
                String tempsex = rs.getString("sportsex");
                Integer tempage;
                if(rs.getInt("sportage")>0)
                    tempage=rs.getInt("sportage");
                else
                    tempage=null;
                model.addRow(new Object[]{tempid, tempname, tempsex, tempage});
            }
        }catch(Exception e){
        showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        refreshSports();
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void editFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_editFrameWindowClosing

    private void submitInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInsertActionPerformed
        
        String sname=insertName.getText();
        String ssex=(String)insertSex.getSelectedItem();
        Integer sage = (int)insertAge.getValue();
        
        try{
            if(sname.equals(""))
                throw new Exception("Please enter a name.");
            if(ssex.equalsIgnoreCase("Any"))
                ssex = null;
            if((sage==0))
                sage = null;
        PreparedStatement ps = cn.prepareStatement("SELECT * FROM insert_sports(?, ?, ?)");
        ps.setObject(1, sname);
        ps.setObject(2, ssex);
        ps.setObject(3, sage);
        ps.executeQuery();
        
        insertFrame.setVisible(false);
        insertFrame.dispose();
        closePopup();
        refreshSports();
        } catch(Exception e){
            showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_submitInsertActionPerformed

    private void insertFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_insertFrameWindowClosing
        closePopup();
    }//GEN-LAST:event_insertFrameWindowClosing

    private void refreshSports(){
        DefaultTableModel model = (DefaultTableModel) sportsTable.getModel();
        try{Class.forName(SportsDB.driverClassName);
            while(model.getRowCount()>0)
                model.removeRow(0);
            Statement statement = cn.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM select_sports(1, NULL, NULL,NULL)");
            while(rs.next()){
                int id = rs.getInt("sportid");
                String name = rs.getString("sportname");
                String sex = rs.getString("sportsex");
                Integer age;
                if(rs.getInt("sportage")>0)
                    age=rs.getInt("sportage");
                else
                    age=null;
                model.addRow(new Object[]{id, name, sex, age});
            }
            if(sportsTable.getRowCount()>0)
                sportsTable.setRowSelectionInterval(0, 0);
            else
                showMessageDialog(null, "No entries for table, please add some!");
            nameTextfield.setText("");
            sexCombobox.setSelectedIndex(2);
            ageSpinner.setValue(0);
            idRadioButton.setSelected(true);
        }catch(Exception e){
         showMessageDialog(null, e.getMessage());
        }
    }
    
    private void openPopup(){
        newSportButton.setEnabled(true);
        editSportButton.setEnabled(true);
        sportsTable.setEnabled(true);
        searchButton.setEnabled(true);
        resetButton.setEnabled(true);
    }
    
    private void closePopup(){
        newSportButton.setEnabled(true);
        editSportButton.setEnabled(true);
        sportsTable.setEnabled(true);
        searchButton.setEnabled(true);
        resetButton.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JSpinner editAge;
    private javax.swing.JFrame editFrame;
    private javax.swing.JTextField editName;
    private javax.swing.JComboBox<String> editSex;
    private javax.swing.JButton editSportButton;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JSpinner insertAge;
    private javax.swing.JFrame insertFrame;
    private javax.swing.JTextField insertName;
    private javax.swing.JComboBox<String> insertSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JButton newSportButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sexCombobox;
    private javax.swing.ButtonGroup sortButtonGroup;
    private javax.swing.JTable sportsTable;
    private javax.swing.JButton submitEdit;
    private javax.swing.JButton submitInsert;
    // End of variables declaration//GEN-END:variables
}
